services:
  web:
    image: node:22
    container_name: doorbell_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["node", "webserver.js"]
    environment:
      - NODE_ENV=production
      - DOORBELL_PORT=${DOORBELL_PORT}
    restart: unless-stopped
